function handler(event) {
    var request = event.request;
    var host = request.headers.host.value;
    var uri = request.uri;

    // Check if the request is for the naked domain (e.g., tapoapartamenty.pl).
    // Note: This JavaScript code runs in CloudFront and cannot directly access Terraform variables.
    // We hardcode the naked domain and www domain here based on the expected values.
    if (host === 'tapoapartamenty.pl') {
        var response = {
            statusCode: 301,
            statusDescription: 'Moved Permanently',
            headers: {
                'location': { value: 'https://www.tapoapartamenty.pl' + uri },
                // Recommended HSTS header for security
                'strict-transport-security': { value: 'max-age=31536000; includeSubdomains; preload' }
            }
        };
        return response;
    }

    // Rewrite clean URLs to the prerendered .html files generated by adapter-static.
    // This preserves SEO metadata by serving the route-specific HTML instead of a SPA shell.
    if (uri !== '/' && !uri.includes('.', 1)) {
        if (uri.endsWith('/')) {
            request.uri = uri.slice(0, -1) + '.html';
        } else {
            request.uri = uri + '.html';
        }
    }

    return request;
}
